// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SFTracker.Data;

#nullable disable

namespace SFTracker.Migrations
{
    [DbContext(typeof(SFTrackerDbContext))]
    [Migration("20260121165628_AddIsSloopedToFactoryRecipe")]
    partial class AddIsSloopedToFactoryRecipe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("SFTracker.Models.DbPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SinkPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tier")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("SFTracker.Models.DbRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAlternate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("TimeSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("SFTracker.Models.DbRecipeInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("RecipeId", "PartId")
                        .IsUnique();

                    b.ToTable("RecipeInputs");
                });

            modelBuilder.Entity("SFTracker.Models.DbRecipeOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("RecipeId", "PartId")
                        .IsUnique();

                    b.ToTable("RecipeOutputs");
                });

            modelBuilder.Entity("SFTracker.Models.Factory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NetworkId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Sorting")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NetworkId");

                    b.HasIndex("Sorting");

                    b.ToTable("Factories");
                });

            modelBuilder.Entity("SFTracker.Models.FactoryInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmountPerMinute")
                        .HasColumnType("REAL");

                    b.Property<int>("FactoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("PartId");

                    b.ToTable("FactoryInputs");
                });

            modelBuilder.Entity("SFTracker.Models.FactoryOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmountPerMinute")
                        .HasColumnType("REAL");

                    b.Property<int>("FactoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("PartId");

                    b.ToTable("FactoryOutputs");
                });

            modelBuilder.Entity("SFTracker.Models.FactoryRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FactoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSlooped")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("IsActive");

                    b.HasIndex("RecipeId");

                    b.HasIndex("FactoryId", "RecipeId");

                    b.ToTable("FactoryRecipes");
                });

            modelBuilder.Entity("SFTracker.Models.FactoryRecipeInputOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FactoryRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeInputId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeInputId");

                    b.HasIndex("FactoryRecipeId", "RecipeInputId")
                        .IsUnique();

                    b.ToTable("FactoryRecipeInputOverrides");
                });

            modelBuilder.Entity("SFTracker.Models.FactoryRecipeOutputOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FactoryRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeOutputId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeOutputId");

                    b.HasIndex("FactoryRecipeId", "RecipeOutputId")
                        .IsUnique();

                    b.ToTable("FactoryRecipeOutputOverrides");
                });

            modelBuilder.Entity("SFTracker.Models.Network", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Networks");
                });

            modelBuilder.Entity("SFTracker.Models.DbRecipeInput", b =>
                {
                    b.HasOne("SFTracker.Models.DbPart", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFTracker.Models.DbRecipe", "Recipe")
                        .WithMany("Inputs")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SFTracker.Models.DbRecipeOutput", b =>
                {
                    b.HasOne("SFTracker.Models.DbPart", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFTracker.Models.DbRecipe", "Recipe")
                        .WithMany("Outputs")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SFTracker.Models.Factory", b =>
                {
                    b.HasOne("SFTracker.Models.Network", "Network")
                        .WithMany("Factories")
                        .HasForeignKey("NetworkId");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("SFTracker.Models.FactoryInput", b =>
                {
                    b.HasOne("SFTracker.Models.Factory", "Factory")
                        .WithMany("Inputs")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFTracker.Models.DbPart", "Part")
                        .WithMany("FactoryInputs")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factory");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("SFTracker.Models.FactoryOutput", b =>
                {
                    b.HasOne("SFTracker.Models.Factory", "Factory")
                        .WithMany("Outputs")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFTracker.Models.DbPart", "Part")
                        .WithMany("FactoryOutputs")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factory");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("SFTracker.Models.FactoryRecipe", b =>
                {
                    b.HasOne("SFTracker.Models.Factory", "Factory")
                        .WithMany("Recipes")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFTracker.Models.DbRecipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factory");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SFTracker.Models.FactoryRecipeInputOverride", b =>
                {
                    b.HasOne("SFTracker.Models.FactoryRecipe", "FactoryRecipe")
                        .WithMany("InputOverrides")
                        .HasForeignKey("FactoryRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFTracker.Models.DbRecipeInput", "RecipeInput")
                        .WithMany()
                        .HasForeignKey("RecipeInputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FactoryRecipe");

                    b.Navigation("RecipeInput");
                });

            modelBuilder.Entity("SFTracker.Models.FactoryRecipeOutputOverride", b =>
                {
                    b.HasOne("SFTracker.Models.FactoryRecipe", "FactoryRecipe")
                        .WithMany("OutputOverrides")
                        .HasForeignKey("FactoryRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFTracker.Models.DbRecipeOutput", "RecipeOutput")
                        .WithMany()
                        .HasForeignKey("RecipeOutputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FactoryRecipe");

                    b.Navigation("RecipeOutput");
                });

            modelBuilder.Entity("SFTracker.Models.DbPart", b =>
                {
                    b.Navigation("FactoryInputs");

                    b.Navigation("FactoryOutputs");
                });

            modelBuilder.Entity("SFTracker.Models.DbRecipe", b =>
                {
                    b.Navigation("Inputs");

                    b.Navigation("Outputs");
                });

            modelBuilder.Entity("SFTracker.Models.Factory", b =>
                {
                    b.Navigation("Inputs");

                    b.Navigation("Outputs");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("SFTracker.Models.FactoryRecipe", b =>
                {
                    b.Navigation("InputOverrides");

                    b.Navigation("OutputOverrides");
                });

            modelBuilder.Entity("SFTracker.Models.Network", b =>
                {
                    b.Navigation("Factories");
                });
#pragma warning restore 612, 618
        }
    }
}
